### ISSUE TITLE
Inventory not updating after opening shulker box

### ISSUE THREAD

**Issue by waibelmarcus** [lMartin3/BetterShulkerBoxes#11]
After opening a shulker box from within the inventory picked up items don't show up until you move an item or eat something.
BSB version 2.14.5 with Minecraft 1.17

**Comment by 23Luzi23** [comment]
I don't think it's the plugin. I tested version 2.14.5 without other plugins on 1.16.5 and 1.17.1 Paper and Spigot. This problem does not occur in version 1.16.5.

**Comment by lMartin3** [comment]
Sorry for the late reply, I am currently working on a rewritten version of the plugin. You can view at https://github.com/lMartin3/BetterShulkerBoxesRewritten
