### ISSUE TITLE
Purple Shulkerbox can't be opened

### ISSUE THREAD

**Issue by Hutch79** [lMartin3/BetterShulkerBoxes#12]
Hey
I found a bug that the purple shulkerbox cant be opened at all.
Every other color works as intended.

**Comment by lMartin3** [comment]
Sorry for the late reply, I am currently working on a rewritten version of the plugin. You can view at https://github.com/lMartin3/BetterShulkerBoxesRewritten

**Comment by Hutch79** [comment]
No problem.
Is there an estimated time when it will be finished?

**Comment by lMartin3** [comment]
You can download the latest version at https://github.com/lMartin3/BetterShulkerBoxesRewritten/releases/tag/3.0.0

**Comment by Hutch79** [comment]
Thanks!
Is this a tested version? (I guess not, but better asking than pretending ^^)

**Comment by lMartin3** [comment]
Yes it is, everything should work as intended though. The production-ready release will be published once I make 100% sure there are no bugs.
If you have any issues please let me know!

**Comment by Hutch79** [comment]
I will, that's the reason why I asked ^^
Thanks for your reply!
