### ISSUE TITLE
[Bug] Dupping items

### ISSUE THREAD

**Issue by nicuch** [lMartin3/BetterShulkerBoxes#6]
Hello!
I have this ugly bug, found by one of my staff (luckily) that shulker boxes are being duped.
So, I have this plugin called InteractiveChat where players can show their inventories/ender chests in chat. The players can then click the chat and that opens an inventory that shows the items (cloned items) a player have (had). Well, when a player right click an shulker box, in that inventory, the shulker box is then transfered to his inventory. That can create infinite, duped, shulker boxes.
One fix might be simply to listen for event on higher prority (that means that plugins with normal or lower prority have time to cancel the click event first) and ditch the event.isCancelled() by using 'ignoreCancelled' (that will force the event to not run if is cancelled).
https://github.com/lMartin3/BetterShulkerBoxes/blob/4902000597bfedccb686c1735a979ec9f70f4e5f/src/main/java/me/rektb/bettershulkerboxes/events/InteractEvent.java#L86
```@EventHandler(eventPriority = EventPriority.HIGHEST, ignoreCancelled = true)```

**Comment by lMartin3** [comment]
Thanks for reporting the bug! Going to fix it now.

**Comment by lMartin3** [comment]
I've applied the changes you suggested and released version 2.13.1. You can download it [here](https://www.spigotmc.org/resources/bsb-better-shulker-boxes.58837/update?update=330957). I can not test if it works as I don't have the plugin you use, so I will leave this issue open. Please test it and let me know if it worked.

**Comment by nicuch** [comment]
Its fixed now, thank you for the fast fix! 😄
