### ISSUE TITLE
Unable to move shulker boxes within your inventory when you have one open (placed down)

### ISSUE THREAD

**Issue by JuanDelPueblo** [lMartin3/BetterShulkerBoxes#7]
My players are complaining that they are unable to move shulker boxes within their inventory (not into the shulker inventory, simply moving within the player's inventory) when they have opened one while placed. This appears to be a inconvenience to my players, so if this can be fixed it would be welcome.

**Comment by lMartin3** [comment]
Hi, thanks for reporting the bug, I will have a look at it as soon as possible.

**Comment by lMartin3** [comment]
I could not recreate the issue. Although players can't move shulker boxes inside their inventory while having one open in hand, they can still move them while having a (placed) shulkerbox inventory open.
I will leave this issue open for now.
