### ISSUE TITLE
Dupe glitch

### ISSUE THREAD

**Issue by DESPEL** [lMartin3/BetterShulkerBoxes#9]
Steps to replicate:
1.  Place items inside a shulkerbox
![image](https://user-images.githubusercontent.com/52083283/91673088-1c380600-eae7-11ea-984d-df7955dc920f.png)
2. Open it and change it to the second hand at the same time, until it disappears from your inventory
![image](https://user-images.githubusercontent.com/52083283/91673105-3540b700-eae7-11ea-93a9-bc7ad3814bbd.png)
3. The Shulker GUI should be open, now take the item
![image](https://user-images.githubusercontent.com/52083283/91673115-4c7fa480-eae7-11ea-9e6a-7f00871bb662.png)
4. Close the GUI, the shulkerbox will appear on your second hand
![image](https://user-images.githubusercontent.com/52083283/91673120-5e614780-eae7-11ea-809d-c42ddff18be9.png)
5. Open that shulkerbox
![image](https://user-images.githubusercontent.com/52083283/91673124-6a4d0980-eae7-11ea-84c9-539dcbf77144.png)
The items you took at step 3 will be inside the box.
6. Repeat

**Comment by lMartin3** [comment]
Thanks for reporting the bug!

**Comment by lMartin3** [comment]
I was able to replicate the bug successfully with the steps provided.

**Comment by EliShiffrin** [comment]
I've reproduced this bug following the given steps today (7/11/2021) on Minecraft v1.17.1.
